# Install pre-commit hooks via:
# pre-commit install

# yapf = yet another python formatter
repos:
- repo: https://github.com/pre-commit/mirrors-yapf
  rev: v0.30.0
  hooks:
  - id: yapf
    name: yapf
    args: ["-i"]

-   repo: https://github.com/PyCQA/pylint
    rev: pylint-2.6.0
    hooks:
    -   id: pylint
        language: system
        exclude: &exclude_files >
          (?x)^(
              start.py|
              tests/.*(?<!\.py)$
          )$